### PR TITLE
Add self-contained neovim plugin for nix/flake users

### PR DESCRIPTION
**Pull request by jwoudenberg**
Hi @faldor20, thank you for all your work on this plugin, I've recently set this up with Neovim and the highlighting has been working like a charm.

I'm also using Nix flakes, and I build a Neovim plugin from the components you're offering in this library. That way there's just a single thing to install. I think that might be useful for other Roc+Neovim+Nix users (don't know how many folks live on _that_ intersection), so I thought I'd offer to contribute this back. Of course no bad feelings if you don't want it, or would like to see some changes!

### CODE REVIEW

**Comment by faldor20** [comment]
Looks great, I don't have neovim setup using nix so I'm not going to test this, but I'll just assume you did a good job :)

**Comment by jwoudenberg** [comment]
I'm running this as we speak! And I'll be happy to support if folks with nix/neovim setups write in!

**Comment by nat-418** [comment]
> I'm running this as we speak! And I'll be happy to support if folks with nix/neovim setups write in!

you may be interested in my efforts to get roc support with nvim-treesitter, nvim-treesitter-textobjects, etc.

https://github.com/faldor20/tree-sitter-roc/pull/16
https://github.com/nvim-treesitter/nvim-treesitter-textobjects/pull/590
https://github.com/nvim-treesitter/nvim-treesitter/pull/6381

**Comment by jwoudenberg** [comment]
Nice, I think that gets most of the same benefits in a better way. Just the filetype addition remains, but that I can keep in my vim config. I'll close this!

**Comment by nat-418** [comment]
> Nice, I think that gets most of the same benefits in a better way. Just the filetype addition remains, but that I can keep in my vim config. I'll close this!

I have an open PR in Vim adding the Roc filetype, which will eventually land in downstream Neovim.

**Pull request closed without merging**
