### PR TITLE
Updates to highlights

### PR DESCRIPTION
**Pull request by LoipesMas**
- Added some queries to `highlights.scm`. I'm not sure which capture names to use. On one hand you'd want them to be accurate, but on the other hand it's better if the editor (Neovim in my case) already has colors set up for that capture (so that the user isn't met with all-white code, thinking that the tree-sitter doesn't work). For example, I think it makes sense to distinguish definitions from normal variables, but I haven't found a good capture for that.
Question: should `queries/highlights.scm` and `neovim/queries/roc/highlights.scm` be in sync? If so, I'll need to copy the file before merging.
- Added support for file imports
- Added "!=" and "%" operators

Many things are still missing, but it's 90% there for most cases!

### CODE REVIEW

**Comment by faldor20** [comment]
Ideally they should be in sync, just for the normal queries i used color names for helix and the neovim copy has names for neovim

**Comment by faldor20** [comment]
If you could sync them up that'd be great, otherwise I can do that myself

**Comment by LoipesMas** [comment]
Updated neovim queries! The only difference was the order of some queries, which I changed anyway, so I just copied the file over

**Comment by faldor20** [comment]
There are a few things that need to change with this. Because the main highlights are for helix, the new queries variable names you've added won't work. Also the ordering within the file has the opposite prescidence in helix vs neovim. 

I appreciate your additional queries and the bugs you've fixed but I think this still needs a little bit of work to get everything working properly in both editors. I realise I need to totally redo the query names for neovim I've started a little query rename and cleanup and will make another PR for the that.

If you want to adjust this to take out the changes to the queries I'll merge in the updated Grammer and I'll sort out the query overhaul shortly. 

Thanks again for your help and bringing this to my attention 😄

**Comment by LoipesMas** [comment]
> Because the main highlights are for helix, the new queries variable names you've added won't work. Also the ordering within the file has the opposite prescidence in helix vs neovim.

Ah, I thought they were fully compatible.



> If you want to adjust this to take out the changes to the queries I'll merge in the updated Grammer and I'll sort out the query overhaul shortly.

So you want me to just revert the highlights files, right?

**Comment by faldor20** [comment]
I've extended your PR with the reworked queries could you take a look and test it in neovim? If you are happy with it I'll merge that with your additions and the reworked queries
https://github.com/faldor20/tree-sitter-roc/pull/3

**Comment by faldor20** [comment]
> > Because the main highlights are for helix, the new queries variable names you've added won't work. Also the ordering within the file has the opposite prescidence in helix vs neovim.
> 
> Ah, I thought they were fully compatible.

I know It's a real pain. To be fair, it's neovim that doesn't match tree-sitter not helix. Painful nonetheless though

**Comment by LoipesMas** [comment]
There were few issues with the neovim highlights:
1. `#set! priority` needs to be in parenthesized
2. `import_path` and `import_as` were not highlighted
3. declaration highlight was being overwritten by variable highlight, so I removed the priority setting. Or would it be better to give variable an even lower priority?

All fixed and pushed here

**Comment by faldor20** [comment]
I just added those import changes to the highlights for helix.
I would suggest making variable even lower, those last few should all be the lowest priority.
Once that's done I'm happy to merge this. Thanks for your work here :)

**Comment by LoipesMas** [comment]
Done! :tada:

**Pull request merged**
