### PR TITLE
fix(neovim): follow nvim-treesitter norms

### PR DESCRIPTION
**Pull request by nat-418**

### CODE REVIEW

**Comment by faldor20** [comment]
Hey, can you merge main into this branch so you aren't removing my changes to injections.scm
Also please provide some description of why this should be merged, as far as i can tell tree-sitter was working in neovim

**Comment by faldor20** [comment]
Oh, also if you are going to replace the existing files please remove them in this PR rather than leaving them there

**Comment by nat-418** [comment]
> Hey, can you merge main into this branch so you aren't removing my changes to injections.scm Also please provide some description of why this should be merged, as far as i can tell tree-sitter was working in neovim

basically I wanted to upstream the work in your repo into the nvim-treesitter ecosystem of tools, so that neovim users can install the roc stuff the same way they do everything else. that means changing how queries are written, etc. if that doesn't interest you I will just maintain my own fork with the modifications necessary

**Comment by faldor20** [comment]
No, not at all, that sounds like a good addition. I just wanted to understand what was changing and why. 
Sync up injections.scm with master and remove the files you're replacing and I'll merge it in, thanks for helping out the neovim folks :)

**Comment by nat-418** [comment]
> Oh, also if you are going to replace the existing files please remove them in this PR rather than leaving them there

I'm sorry, I don't understand what you mean here. What do you want me to do?

**Comment by faldor20** [comment]
Thanks for this addition, I just made the changes I suggested to move things along :)

**Pull request merged**
